language: node_js
node_js:
- lts/*
script:
- yarn test
- npm run test
branches:
  except:
  - legacy
  only:
  - main
deploy:
  provider: heroku
  api_key:
    secure: gUxzHWfiqcGQKo7OPK9/EfmblAEY8BL4RaDYrBxz5HCg7etxGDrT4Nyp5351JiO0lebhYa3yUaEHCB/stUzSyIRJTqlSGxltvC6SMCGlnyDQNCEzae7VUVtZYoqklBg1Gdq1rhDKzjG39mUSe94dTeAIOy+JY0Q/F/op8fHR3T/akk85eJPcbEee/wlg2FXNhnflpoDZ9RxDTXwiDcvRuKZ1niEncAf5miH3tofA5MFGVyhTRs+gcXX40EFdIuRiRxiu12APlin5t7j+VpSDHa1lHVaZPMkrj2lp83IAw2vxKYDbGWQE2+o31SbSQaeOoKsPqITD+ty5Il/s3y1gb1iQNpzVZWmcMcKPkdY+ev1Yp59coHyEIALktV2Wbu6WmPQI9NLts1Uqd4ol5hKogJ0XVHNa0H3qh20cucFw5PbKet5GT+hDpCEHwdQ41gGPvd5QO/XOmWPM3zvdFtSbg7h56hdGsWshDpfIx2MkS48uiXa6q4zdPO/ZIeJTzsb5r8yXE3VoVW6RTi5nWy6IA6A0qsE8jHVjxY1/79ZrMtjjgobJUqU+j+7oNif0/vjQL6pXakFqop3hjJvucWkjgDyeUxwlv1KBMf+jDnRm+INuoqhBmrdHnd/etIOy4HlSmDdJRpv+yodW/Vn6uknTMkOcCk7/nuOCBhN4y59LrpA=
