language: node_js
node_js:
- lts/*
script:
- yarn test
branches:
  except:
  - legacy
  only:
  - main
services: 
  - mongodb
deploy:
  provider: heroku
  app: api-perf-analytics
  api_key:
    secure: r2bmWBaw9DMS43gQynZLmXi7in4D4sKg/VpbjuwYvVe3nwS88/1en1MKM+xV7FQbO6ll6+1bn/AzbebV8hqjf40PBPaTYMPPgaCYXEbpeDZ4cOHViu/qER3NANK0I/nLbw0IRL76V9Cm2473gLTq6ENZVJg9Sg003+2HGoQJHDGrVoh44uuKOrYykDRyVWPcysz2KOK1b0kQMVunj9d6WK2ptlNAKX/THKl2RiQIv7sgMxq3g61oPJWrNtUphwc1gGNGDfea0/Cv2gHnlZt4TfzDzTec3guHuCiEkHjl3wC86gj841FUpG4vNkNyK7e54hlGj+xhorIxEBC7EGHpRdJX9aMu6zuA9bpIB/iQYb9ny0EcIvuTux0D+Gs6QnyDt70fVEWneiE6aF3aAaHWX14/kK5/pYD1lUJwnYhsjN4eyklssE/BNft2/n89yZ+1IQIhd5XT6too+C/7/cXFQH6Zu6VBGWxDU8RLo46uUsZ40LtroPBN91c6pu06iNHtPlDgiKz4forMokVLJ1W2HLY672LjZHVJ9KtFbdiXEcclra8dCoqghLZhpFnmRnB9IjLzuq+ByPsl/rqNVj21wv7SdVULRzdcVB01xRB10h5ZWE686M7xR7YxtVKBzbMzKQbWjBu34s6NvwZoqYu2BIbe86BaoRdrA8Dq69HzbJo=
